"""Fix issues in default cogwheel_pe/meta.yaml generated by grayskull.

* python-lalsimulation missing because it's not in pyproject.toml
* package name `cogwheel_pe` should be `cogwheel`
"""
with open('cogwheel_pe/meta.yaml') as file:
	text = file.read()


# Add python-lalsimulation to conda requirements
target = """
  run:
    - python >=3.9"""
new = """
    - python-lalsimulation"""
text = text.replace(target, target + new)


# Rename default package name `cogwheel_pe` to `cogwheel`
target = """
test:
  imports:
    - cogwheel_pe"""
new = """
test:
  imports:
    - cogwheel"""
text = text.replace(target, new)

with open('cogwheel_pe/meta.yaml', 'w') as file:
	file.write(text)
